version: '2.1'

services:
  sn-discovery-service:
    image: social-network/sn-discovery-service:latest
    restart: always
    ports:
      - "8761:8761"

  sn-gateway-service:
    image: social-network/sn-gateway-service:latest
    restart: always
    ports:
      - "8765:8765"
    depends_on:
      - sn-discovery-service

  sn-monitor-dashboard:
    image: social-network/sn-monitor-dashboard:latest
    restart: always
    ports:
      - "7979:7979"
    depends_on:
      - sn-discovery-service

  sn-auth-service:
    environment:
      SN_STORAGE_SERVICE_PASSWORD: $SN_STORAGE_SERVICE_PASSWORD
      SN_USER_SERVICE_PASSWORD: $SN_USER_SERVICE_PASSWORD
      SN_USER_QUERY_SERVICE_PASSWORD: $SN_USER_QUERY_SERVICE_PASSWORD
    image: social-network/sn-auth-service:latest
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - sn-gateway-service

  sn-user-service:
    environment:
      SN_USER_SERVICE_PASSWORD: $SN_USER_SERVICE_PASSWORD
    image: social-network/sn-user-service:latest
    restart: always
    depends_on:
      - sn-gateway-service

  sn-user-query-service:
    environment:
      SN_USER_QUERY_SERVICE_PASSWORD: $SN_USER_QUERY_SERVICE_PASSWORD
    image: social-network/sn-user-query-service:latest
    restart: always
    depends_on:
      - sn-gateway-service

  sn-storage-service:
    environment:
      SN_STORAGE_SERVICE_PASSWORD: $SN_STORAGE_SERVICE_PASSWORD
    image: social-network/sn-storage-service:latest
    restart: always
    depends_on:
      - sn-gateway-service