server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://sn-discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      clientId: sn-user-query-service
      clientSecret: SN_USER_QUERY_SERVICE
      accessTokenUri: http://sn-auth-service:9999/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    ua.social.network.query: DEBUG
    org:
      hibernate:
        type: trace
        tool:
          hbm2ddl: debug

dataSource:
  dialect: org.hibernate.dialect.HSQLDialect
  hbm2ddl: update
  dbName: user