info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://sn-auth-service:9999/uaa/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://sn-discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    sn-auth-service:
      path: /uaa/**
      url: http://sn-auth-service:9999
      sensitiveHeaders: Cookie,Set-Cookie
    sn-community-service:
      path: /api/**
      serviceId: sn-community-service
    sn-community-query-service:
      path: /api/**
      serviceId: sn-community-query-service
    sn-user-service:
      path: /api/**
      serviceId: sn-user-service
    sn-user-query-service:
      path: /api/**
      serviceId: sn-user-query-service

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO