server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

dataSource:
  dialect: org.hibernate.dialect.HSQLDialect
  hbm2ddl: none
  dbName: user