info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    sn-query-service:
      path: /sn-query-service/**
      serviceId: sn-query-service

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO