server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

dataSource:
  dialect: org.hibernate.dialect.HSQLDialect
  hbm2ddl: update
  dbName: community

logging:
  level:
    org:
      hibernate:
        type: trace
        tool:
          hbm2ddl: debug