server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://sn-discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

dataSource:
  dialect: org.hibernate.dialect.HSQLDialect
  hbm2ddl: update
  dbName: user

logging:
  level:
    ua.social.network.query: DEBUG
    org:
      hibernate:
        type: trace
        tool:
          hbm2ddl: debug

filesRootPath: /tmp